language: java
jdk: openjdk12

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn -B -DskipTests=true clean deploy -Prelease

deploy:
  - provider: releases
    token: "${GITHUB_TOKEN}"
    file_glob: true
    file: target/*.jar
    cleanup: true
    on:
      repo: "${TRAVIS_REPO_SLUG}"
      branch: master
      tags: true
