name: Build branches

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scm
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
          cache: maven

      - name: Configure Maven Settings
        run : cp .github/workflows/settings.xml $HOME/.m2/settings.xml

      - name: Compute version
        id: compute_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          release_branches: ".*"

      - name: Build with Maven
        run:  |
          echo "[INFO] if merged, this build would be deployed in koson:${{ steps.compute_version.outputs.new_version }}"
          mvn clean test